# Generated by Django 6.0.2 on 2026-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='address_complement',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='address_label',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='address_neighborhood',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='address_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='address_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='address_street',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='order',
            name='address_zipcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/prescriptions/'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
